version: "3.9"
services:
  goodstock_api_customers_db:
    image: postgres:14
    env_file:
      - api_customers.env
    links:
      - goodstock_api_customers

  goodstock_api_customers:
    build: ./api/customers/
    container_name: goodstock_api_customers
    # volumes:
    #   - ./api/customers:/app
    ports:
      - 3001:3001
    env_file:
      - api_customers.env
