version: "3.9"
services:
  goodstock_api_customers_db:
    image: postgres:14
    container_name: goodstock_api_customers_db
    env_file:
      - api_customers.env
    links:
      - goodstock_api_customers

  goodstock_api_customers:
    build: ./api/customers/
    container_name: goodstock_api_customers
    # volumes:
    #   - ./api/customers:/app
    ports:
      - 3001:3001
    env_file:
      - api_customers.env

  goodstock_api_products_db:
    image: mongo
    container_name: goodstock_api_products_db
    env_file:
      - api_products.env
    links:
      - goodstock_api_products

  goodstock_api_products:
    build: ./api/products/
    container_name: goodstock_api_products
    # volumes:
    #   - ./api/products:/app
    ports:
      - 3001:3001
    env_file:
      - api_products.env
