version: "3.9"
services:
  # Main Containers
  goodstock_backend:
    container_name: goodstock_backend
    build: ./backend
    ports:
      - 443:443     # HTTPS server
    env_file:
      - backend.env
    links:
      - goodstock_api_main
  
  goodstock_api_main:
    container_name: goodstock_api_main
    build: ./api/main/
    ports:
      - 3000:3000
    # volumes:
    #   - ./api/main:/app
    env_file:
      - api_main.env

  # Databases
  goodstock_api_customers_db:
    container_name: goodstock_api_customers_db
    image: postgres
    volumes:
      - ./db/api-customers:/var/lib/postgresql/data
    env_file:
      - api_customers.env
    links:
      - goodstock_api_customers

  goodstock_api_products_db:
    container_name: goodstock_api_products_db
    image: mongo
    volumes:
      - ./db/api-products:/data/db
    env_file:
      - api_products.env
    links:
      - goodstock_api_products

  # APIs
  goodstock_api_customers:
    container_name: goodstock_api_customers
    build: ./api/customers/
    # volumes:
    #   - ./api/customers:/app
    env_file:
      - api_customers.env

  goodstock_api_products:
    container_name: goodstock_api_products
    build: ./api/products/
    # volumes:
    #   - ./api/products:/app
    env_file:
      - api_products.env
